-- GENERATED by tools/gen_spells.py from .claude/docs/{druid,paladin,priest,shaman}.json - do not edit by hand.
-- Overrides, combat-log aliases and spells the tooltips do not describe live in Parsers/Spells_Manual.lua.
local name, addon = ...;
local S, T = addon.Spells, addon.SpellType;

-- Healing Touch
S:Define(5185, T.DRUID, "Healing Touch", { coeff = 0.429, base = 47, mana = 25, cast = 1.5 }); -- Rank 1
S:Define(5186, T.DRUID, "Healing Touch", { coeff = 0.571, base = 106, mana = 55, cast = 2 }); -- Rank 2
S:Define(5187, T.DRUID, "Healing Touch", { coeff = 0.714, base = 210, mana = 110, cast = 2.5 }); -- Rank 3
S:Define(5188, T.DRUID, "Healing Touch", { coeff = 0.857, base = 375, mana = 190, cast = 3 }); -- Rank 4
S:Define(5189, T.DRUID, "Healing Touch", { coeff = 1, base = 563, mana = 280, cast = 3.5 }); -- Rank 5
S:Define(6778, T.DRUID, "Healing Touch", { coeff = 1, base = 727, mana = 350, cast = 3.5 }); -- Rank 6
S:Define(8903, T.DRUID, "Healing Touch", { coeff = 1, base = 920, mana = 425, cast = 3.5 }); -- Rank 7
S:Define(9758, T.DRUID, "Healing Touch", { coeff = 1, base = 1199, mana = 520, cast = 3.5 }); -- Rank 8
S:Define(9888, T.DRUID, "Healing Touch", { coeff = 1, base = 1545, mana = 630, cast = 3.5 }); -- Rank 9
S:Define(9889, T.DRUID, "Healing Touch", { coeff = 1, base = 1946, mana = 755, cast = 3.5 }); -- Rank 10
S:Define(25297, T.DRUID, "Healing Touch", { coeff = 1, base = 2332, mana = 840, cast = 3.5 }); -- Rank 11

-- Rejuvenation
S:Define(774, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 8, mana = 25 }); -- Rank 1
S:Define(1058, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 12, mana = 40 }); -- Rank 2
S:Define(1430, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 23, mana = 75 }); -- Rank 3
S:Define(2090, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 32, mana = 105 }); -- Rank 4
S:Define(2091, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 42, mana = 135 }); -- Rank 5
S:Define(3627, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 51, mana = 160 }); -- Rank 6
S:Define(8910, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 71, mana = 195 }); -- Rank 7
S:Define(9839, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 94, mana = 235 }); -- Rank 8
S:Define(9840, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 124, mana = 280 }); -- Rank 9
S:Define(9841, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 161, mana = 335 }); -- Rank 10
S:Define(25299, T.DRUID, "Rejuvenation", { coeffTick = 0.2, baseTick = 194, mana = 360 }); -- Rank 11

-- Regrowth
S:Define(8936, T.DRUID, "Regrowth", { coeff = 0.286, base = 96, coeffTick = 0.071, baseTick = 13, mana = 70, cast = 2 }); -- Rank 1
S:Define(8938, T.DRUID, "Regrowth", { coeff = 0.286, base = 176, coeffTick = 0.071, baseTick = 22, mana = 125, cast = 2 }); -- Rank 2
S:Define(8939, T.DRUID, "Regrowth", { coeff = 0.286, base = 250, coeffTick = 0.071, baseTick = 32, mana = 170, cast = 2 }); -- Rank 3
S:Define(8940, T.DRUID, "Regrowth", { coeff = 0.286, base = 329, coeffTick = 0.071, baseTick = 42, mana = 210, cast = 2 }); -- Rank 4
S:Define(8941, T.DRUID, "Regrowth", { coeff = 0.286, base = 414, coeffTick = 0.071, baseTick = 52, mana = 250, cast = 2 }); -- Rank 5
S:Define(9750, T.DRUID, "Regrowth", { coeff = 0.286, base = 527, coeffTick = 0.071, baseTick = 68, mana = 305, cast = 2 }); -- Rank 6
S:Define(9856, T.DRUID, "Regrowth", { coeff = 0.286, base = 671, coeffTick = 0.071, baseTick = 88, mana = 370, cast = 2 }); -- Rank 7
S:Define(9857, T.DRUID, "Regrowth", { coeff = 0.286, base = 847, coeffTick = 0.071, baseTick = 113, mana = 445, cast = 2 }); -- Rank 8
S:Define(9858, T.DRUID, "Regrowth", { coeff = 0.286, base = 1021, coeffTick = 0.071, baseTick = 142, mana = 525, cast = 2 }); -- Rank 9

-- Wild Growth
S:Define(408120, T.DRUID, "Wild Growth", { coeffTick = 0.033, baseTick = 48, mana = 550 }); -- Rank 1
S:Define(1238214, T.DRUID, "Wild Growth", { coeffTick = 0.033, baseTick = 70, mana = 755 }); -- Rank 2
S:Define(1238215, T.DRUID, "Wild Growth", { coeffTick = 0.033, baseTick = 97, mana = 1050 }); -- Rank 3

-- Tranquility
S:Define(740, T.DRUID, "Tranquility", { baseTick = 90, mana = 375, cast = -1, cd = true }); -- Rank 1 (no coefficient in JSON)
S:Define(8918, T.DRUID, "Tranquility", { baseTick = 133, mana = 505, cast = -1, cd = true }); -- Rank 2 (no coefficient in JSON)
S:Define(9862, T.DRUID, "Tranquility", { baseTick = 201, mana = 695, cast = -1, cd = true }); -- Rank 3 (no coefficient in JSON)
S:Define(9863, T.DRUID, "Tranquility", { baseTick = 285, mana = 925, cast = -1, cd = true }); -- Rank 4 (no coefficient in JSON)

-- Swiftmend
S:Define(18562, T.DRUID, "Swiftmend", { manaPct = 0.2 }); -- (no coefficient in JSON; tooltip not parsed)

-- Holy Light
S:Define(635, T.PALADIN, "Holy Light", { coeff = 0.714, base = 46, mana = 35, cast = 2.5 }); -- Rank 1
S:Define(639, T.PALADIN, "Holy Light", { coeff = 0.714, base = 88, mana = 60, cast = 2.5 }); -- Rank 2
S:Define(647, T.PALADIN, "Holy Light", { coeff = 0.714, base = 163, mana = 110, cast = 2.5 }); -- Rank 3
S:Define(1026, T.PALADIN, "Holy Light", { coeff = 0.714, base = 299, mana = 190, cast = 2.5 }); -- Rank 4
S:Define(1042, T.PALADIN, "Holy Light", { coeff = 0.714, base = 467, mana = 275, cast = 2.5 }); -- Rank 5
S:Define(3472, T.PALADIN, "Holy Light", { coeff = 0.714, base = 665, mana = 365, cast = 2.5 }); -- Rank 6
S:Define(10328, T.PALADIN, "Holy Light", { coeff = 0.714, base = 922, mana = 465, cast = 2.5 }); -- Rank 7
S:Define(10329, T.PALADIN, "Holy Light", { coeff = 0.714, base = 1243, mana = 580, cast = 2.5 }); -- Rank 8
S:Define(25292, T.PALADIN, "Holy Light", { coeff = 0.714, base = 1580, mana = 660, cast = 2.5 }); -- Rank 9

-- Flash of Light
S:Define(19750, T.PALADIN, "Flash of Light", { coeff = 0.429, base = 51, mana = 35, cast = 1.5 }); -- Rank 1
S:Define(19939, T.PALADIN, "Flash of Light", { coeff = 0.429, base = 72, mana = 50, cast = 1.5 }); -- Rank 2
S:Define(19940, T.PALADIN, "Flash of Light", { coeff = 0.429, base = 109, mana = 70, cast = 1.5 }); -- Rank 3
S:Define(19941, T.PALADIN, "Flash of Light", { coeff = 0.429, base = 160, mana = 90, cast = 1.5 }); -- Rank 4
S:Define(19942, T.PALADIN, "Flash of Light", { coeff = 0.429, base = 234, mana = 115, cast = 1.5 }); -- Rank 5
S:Define(19943, T.PALADIN, "Flash of Light", { coeff = 0.429, base = 308, mana = 140, cast = 1.5 }); -- Rank 6

-- Holy Shock
S:Define(1311606, T.PALADIN, "Holy Shock", { coeff = 0.429, base = 114, mana = 160 }); -- Rank 1
S:Define(20473, T.PALADIN, "Holy Shock", { coeff = 0.429, base = 156, mana = 225 }); -- Rank 2
S:Define(20929, T.PALADIN, "Holy Shock", { coeff = 0.429, base = 230, mana = 275 }); -- Rank 3
S:Define(20930, T.PALADIN, "Holy Shock", { coeff = 0.429, base = 320, mana = 325 }); -- Rank 4

-- Light's Vigil
S:Define(1310911, T.PALADIN, "Light's Vigil", { coeff = 0.143, base = 334, mana = 730, cast = 1.5 }); -- Rank 1
S:Define(1311590, T.PALADIN, "Light's Vigil", { coeff = 0.143, base = 500, mana = 1000, cast = 1.5 }); -- Rank 2
S:Define(1311595, T.PALADIN, "Light's Vigil", { coeff = 0.143, base = 704, mana = 1340, cast = 1.5 }); -- Rank 3

-- Lay on Hands
S:Define(633, T.PALADIN, "Lay on Hands", { cd = true, canCrit = false }); -- Rank 1 (no coefficient in JSON; tooltip not parsed)
S:Define(2800, T.PALADIN, "Lay on Hands", { cd = true, canCrit = false }); -- Rank 2 (no coefficient in JSON; tooltip not parsed)
S:Define(10310, T.PALADIN, "Lay on Hands", { cd = true, canCrit = false }); -- Rank 3 (no coefficient in JSON; tooltip not parsed)

-- Lesser Heal
S:Define(2050, T.PRIEST, "Lesser Heal", { coeff = 0.429, base = 52, mana = 30, cast = 1.5 }); -- Rank 1
S:Define(2052, T.PRIEST, "Lesser Heal", { coeff = 0.571, base = 83, mana = 45, cast = 2 }); -- Rank 2
S:Define(2053, T.PRIEST, "Lesser Heal", { coeff = 0.714, base = 149, mana = 75, cast = 2.5 }); -- Rank 3

-- Heal
S:Define(2054, T.PRIEST, "Heal", { coeff = 0.857, base = 303, mana = 155, cast = 3 }); -- Rank 1
S:Define(2055, T.PRIEST, "Heal", { coeff = 0.857, base = 421, mana = 205, cast = 3 }); -- Rank 2
S:Define(6063, T.PRIEST, "Heal", { coeff = 0.857, base = 543, mana = 255, cast = 3 }); -- Rank 3
S:Define(6064, T.PRIEST, "Heal", { coeff = 0.857, base = 673, mana = 305, cast = 3 }); -- Rank 4

-- Greater Heal
S:Define(2060, T.PRIEST, "Greater Heal", { coeff = 0.857, base = 869, mana = 370, cast = 3 }); -- Rank 1
S:Define(10963, T.PRIEST, "Greater Heal", { coeff = 0.857, base = 1128, mana = 455, cast = 3 }); -- Rank 2
S:Define(10964, T.PRIEST, "Greater Heal", { coeff = 0.857, base = 1436, mana = 545, cast = 3 }); -- Rank 3
S:Define(10965, T.PRIEST, "Greater Heal", { coeff = 0.857, base = 1797, mana = 655, cast = 3 }); -- Rank 4
S:Define(25314, T.PRIEST, "Greater Heal", { coeff = 0.857, base = 1960, mana = 710, cast = 3 }); -- Rank 5

-- Flash Heal
S:Define(2061, T.PRIEST, "Flash Heal", { coeff = 0.429, base = 203, mana = 125, cast = 1.5 }); -- Rank 1
S:Define(9472, T.PRIEST, "Flash Heal", { coeff = 0.429, base = 260, mana = 155, cast = 1.5 }); -- Rank 2
S:Define(9473, T.PRIEST, "Flash Heal", { coeff = 0.429, base = 324, mana = 185, cast = 1.5 }); -- Rank 3
S:Define(9474, T.PRIEST, "Flash Heal", { coeff = 0.429, base = 397, mana = 215, cast = 1.5 }); -- Rank 4
S:Define(10915, T.PRIEST, "Flash Heal", { coeff = 0.429, base = 523, mana = 265, cast = 1.5 }); -- Rank 5
S:Define(10916, T.PRIEST, "Flash Heal", { coeff = 0.429, base = 662, mana = 315, cast = 1.5 }); -- Rank 6
S:Define(10917, T.PRIEST, "Flash Heal", { coeff = 0.429, base = 841, mana = 380, cast = 1.5 }); -- Rank 7

-- Renew
S:Define(139, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 9, mana = 30 }); -- Rank 1
S:Define(6074, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 15, mana = 65 }); -- Rank 2
S:Define(6075, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 25, mana = 105 }); -- Rank 3
S:Define(6076, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 32, mana = 140 }); -- Rank 4
S:Define(6077, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 41, mana = 170 }); -- Rank 5
S:Define(6078, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 54, mana = 205 }); -- Rank 6
S:Define(10927, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 74, mana = 250 }); -- Rank 7
S:Define(10928, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 102, mana = 305 }); -- Rank 8
S:Define(10929, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 134, mana = 365 }); -- Rank 9
S:Define(25315, T.PRIEST, "Renew", { coeffTick = 0.2, baseTick = 166, mana = 410 }); -- Rank 10

-- Prayer of Healing
S:Define(596, T.PRIEST, "Prayer of Healing", { coeff = 0.286, base = 185, mana = 410, cast = 3 }); -- Rank 1
S:Define(996, T.PRIEST, "Prayer of Healing", { coeff = 0.286, base = 274, mana = 560, cast = 3 }); -- Rank 2
S:Define(10960, T.PRIEST, "Prayer of Healing", { coeff = 0.286, base = 412, mana = 770, cast = 3 }); -- Rank 3
S:Define(10961, T.PRIEST, "Prayer of Healing", { coeff = 0.286, base = 583, mana = 1030, cast = 3 }); -- Rank 4
S:Define(25316, T.PRIEST, "Prayer of Healing", { coeff = 0.286, base = 649, mana = 1070, cast = 3 }); -- Rank 5

-- Holy Nova
S:Define(15237, T.PRIEST, "Holy Nova", { coeff = 0.107, base = 53, mana = 185 }); -- Rank 1
S:Define(15430, T.PRIEST, "Holy Nova", { coeff = 0.107, base = 85, mana = 290 }); -- Rank 2
S:Define(15431, T.PRIEST, "Holy Nova", { coeff = 0.107, base = 119, mana = 400 }); -- Rank 3
S:Define(27799, T.PRIEST, "Holy Nova", { coeff = 0.107, base = 163, mana = 520 }); -- Rank 4
S:Define(27800, T.PRIEST, "Holy Nova", { coeff = 0.107, base = 242, mana = 635 }); -- Rank 5
S:Define(27801, T.PRIEST, "Holy Nova", { coeff = 0.107, base = 311, mana = 750 }); -- Rank 6

-- Binding Heal
S:Define(401937, T.PRIEST, "Binding Heal", { coeff = 0.429, base = 260, mana = 155, cast = 1.5 }); -- Rank 1
S:Define(1240770, T.PRIEST, "Binding Heal", { coeff = 0.429, base = 324, mana = 185, cast = 1.5 }); -- Rank 2
S:Define(1240771, T.PRIEST, "Binding Heal", { coeff = 0.429, base = 397, mana = 215, cast = 1.5 }); -- Rank 3
S:Define(1240772, T.PRIEST, "Binding Heal", { coeff = 0.429, base = 523, mana = 265, cast = 1.5 }); -- Rank 4
S:Define(1240773, T.PRIEST, "Binding Heal", { coeff = 0.429, base = 662, mana = 315, cast = 1.5 }); -- Rank 5
S:Define(1240774, T.PRIEST, "Binding Heal", { coeff = 0.429, base = 841, mana = 380, cast = 1.5 }); -- Rank 6

-- Prayer of Mending
S:Define(401859, T.PRIEST, "Prayer of Mending", { base = 172, mana = 210 }); -- Rank 1 (no coefficient in JSON)
S:Define(1240826, T.PRIEST, "Prayer of Mending", { base = 298, mana = 305 }); -- Rank 2 (no coefficient in JSON)
S:Define(1240827, T.PRIEST, "Prayer of Mending", { base = 413, mana = 390 }); -- Rank 3 (no coefficient in JSON)

-- Penance
S:Define(402174, T.PRIEST, "Penance", { coeff = 0.285, base = 184, coeffTick = 0.285, baseTick = 184, mana = 100, cast = -1 }); -- Rank 1
S:Define(1240720, T.PRIEST, "Penance", { coeff = 0.285, base = 291, coeffTick = 0.285, baseTick = 291, mana = 185, cast = -1 }); -- Rank 2
S:Define(1240721, T.PRIEST, "Penance", { coeff = 0.285, base = 482, coeffTick = 0.285, baseTick = 482, mana = 270, cast = -1 }); -- Rank 3
S:Define(1316995, T.PRIEST, "Penance", { coeff = 0.285, base = 673, coeffTick = 0.285, baseTick = 673, mana = 355, cast = -1 }); -- Rank 4

-- Power Word: Shield
S:Define(17, T.PRIEST, "Power Word: Shield", { base = 48, mana = 45, canCrit = false }); -- Rank 1 (no coefficient in JSON)
S:Define(592, T.PRIEST, "Power Word: Shield", { base = 92, mana = 80, canCrit = false }); -- Rank 2 (no coefficient in JSON)
S:Define(600, T.PRIEST, "Power Word: Shield", { base = 162, mana = 130, canCrit = false }); -- Rank 3 (no coefficient in JSON)
S:Define(3747, T.PRIEST, "Power Word: Shield", { base = 236, mana = 175, canCrit = false }); -- Rank 4 (no coefficient in JSON)
S:Define(6065, T.PRIEST, "Power Word: Shield", { base = 302, mana = 210, canCrit = false }); -- Rank 5 (no coefficient in JSON)
S:Define(6066, T.PRIEST, "Power Word: Shield", { base = 381, mana = 250, canCrit = false }); -- Rank 6 (no coefficient in JSON)
S:Define(10898, T.PRIEST, "Power Word: Shield", { base = 485, mana = 300, canCrit = false }); -- Rank 7 (no coefficient in JSON)
S:Define(10899, T.PRIEST, "Power Word: Shield", { base = 608, mana = 355, canCrit = false }); -- Rank 8 (no coefficient in JSON)
S:Define(10900, T.PRIEST, "Power Word: Shield", { base = 768, mana = 425, canCrit = false }); -- Rank 9 (no coefficient in JSON)
S:Define(10901, T.PRIEST, "Power Word: Shield", { base = 928, mana = 500, canCrit = false }); -- Rank 10 (no coefficient in JSON)

-- Desperate Prayer
S:Define(13908, T.PRIEST, "Desperate Prayer", { coeff = 0.429, base = 163, cd = true }); -- Rank 1
S:Define(19236, T.PRIEST, "Desperate Prayer", { coeff = 0.429, base = 296, cd = true }); -- Rank 2
S:Define(19238, T.PRIEST, "Desperate Prayer", { coeff = 0.429, base = 485, cd = true }); -- Rank 3
S:Define(19240, T.PRIEST, "Desperate Prayer", { coeff = 0.429, base = 626, cd = true }); -- Rank 4
S:Define(19241, T.PRIEST, "Desperate Prayer", { coeff = 0.429, base = 894, cd = true }); -- Rank 5
S:Define(19242, T.PRIEST, "Desperate Prayer", { coeff = 0.429, base = 1187, cd = true }); -- Rank 6
S:Define(19243, T.PRIEST, "Desperate Prayer", { coeff = 0.429, base = 1399, cd = true }); -- Rank 7

-- Divine Grace
S:Define(1277370, T.PRIEST, "Divine Grace", { coeff = 0.429, base = 163, cd = true }); -- Rank 1
S:Define(1277371, T.PRIEST, "Divine Grace", { coeff = 0.429, base = 296, cd = true }); -- Rank 2
S:Define(1277372, T.PRIEST, "Divine Grace", { coeff = 0.429, base = 485, cd = true }); -- Rank 3
S:Define(1277374, T.PRIEST, "Divine Grace", { coeff = 0.429, base = 626, cd = true }); -- Rank 4
S:Define(1277376, T.PRIEST, "Divine Grace", { coeff = 0.429, base = 894, cd = true }); -- Rank 5
S:Define(1277377, T.PRIEST, "Divine Grace", { coeff = 0.429, base = 1187, cd = true }); -- Rank 6
S:Define(1277378, T.PRIEST, "Divine Grace", { coeff = 0.429, base = 1399, cd = true }); -- Rank 7

-- Healing Wave
S:Define(331, T.SHAMAN, "Healing Wave", { coeff = 0.429, base = 41, mana = 25, cast = 1.5 }); -- Rank 1
S:Define(332, T.SHAMAN, "Healing Wave", { coeff = 0.571, base = 76, mana = 45, cast = 2 }); -- Rank 2
S:Define(547, T.SHAMAN, "Healing Wave", { coeff = 0.714, base = 138, mana = 80, cast = 2.5 }); -- Rank 3
S:Define(913, T.SHAMAN, "Healing Wave", { coeff = 0.857, base = 267, mana = 155, cast = 3 }); -- Rank 4
S:Define(939, T.SHAMAN, "Healing Wave", { coeff = 0.857, base = 355, mana = 200, cast = 3 }); -- Rank 5
S:Define(959, T.SHAMAN, "Healing Wave", { coeff = 0.857, base = 500, mana = 265, cast = 3 }); -- Rank 6
S:Define(8005, T.SHAMAN, "Healing Wave", { coeff = 0.857, base = 704, mana = 340, cast = 3 }); -- Rank 7
S:Define(10395, T.SHAMAN, "Healing Wave", { coeff = 0.857, base = 995, mana = 440, cast = 3 }); -- Rank 8
S:Define(10396, T.SHAMAN, "Healing Wave", { coeff = 0.857, base = 1366, mana = 560, cast = 3 }); -- Rank 9
S:Define(25357, T.SHAMAN, "Healing Wave", { coeff = 0.857, base = 1615, mana = 620, cast = 3 }); -- Rank 10

-- Lesser Healing Wave
S:Define(8004, T.SHAMAN, "Lesser Healing Wave", { coeff = 0.429, base = 161, mana = 105, cast = 1.5 }); -- Rank 1
S:Define(8008, T.SHAMAN, "Lesser Healing Wave", { coeff = 0.429, base = 234, mana = 145, cast = 1.5 }); -- Rank 2
S:Define(8010, T.SHAMAN, "Lesser Healing Wave", { coeff = 0.429, base = 316, mana = 185, cast = 1.5 }); -- Rank 3
S:Define(10466, T.SHAMAN, "Lesser Healing Wave", { coeff = 0.429, base = 441, mana = 235, cast = 1.5 }); -- Rank 4
S:Define(10467, T.SHAMAN, "Lesser Healing Wave", { coeff = 0.429, base = 626, mana = 305, cast = 1.5 }); -- Rank 5
S:Define(10468, T.SHAMAN, "Lesser Healing Wave", { coeff = 0.429, base = 820, mana = 380, cast = 1.5 }); -- Rank 6

-- Chain Heal
S:Define(1064, T.SHAMAN, "Chain Heal", { coeff = 0.714, base = 263, mana = 260, cast = 2.5 }); -- Rank 1
S:Define(10622, T.SHAMAN, "Chain Heal", { coeff = 0.714, base = 349, mana = 315, cast = 2.5 }); -- Rank 2
S:Define(10623, T.SHAMAN, "Chain Heal", { coeff = 0.714, base = 506, mana = 405, cast = 2.5 }); -- Rank 3

-- Riptide
S:Define(408521, T.SHAMAN, "Riptide", { coeff = 0.214, base = 509, coeffTick = 0.1, baseTick = 89, mana = 245 }); -- Rank 1
S:Define(1239242, T.SHAMAN, "Riptide", { coeff = 0.214, base = 645, coeffTick = 0.1, baseTick = 115, mana = 300 }); -- Rank 2
S:Define(1239243, T.SHAMAN, "Riptide", { coeff = 0.214, base = 841, coeffTick = 0.1, baseTick = 161, mana = 385 }); -- Rank 3

-- Healing Stream Totem
S:Define(5394, T.SHAMAN, "Healing Stream Totem", { baseTick = 5, mana = 40 }); -- Rank 1 (no coefficient in JSON)
S:Define(6375, T.SHAMAN, "Healing Stream Totem", { baseTick = 6, mana = 50 }); -- Rank 2 (no coefficient in JSON)
S:Define(6377, T.SHAMAN, "Healing Stream Totem", { baseTick = 7, mana = 60 }); -- Rank 3 (no coefficient in JSON)
S:Define(10462, T.SHAMAN, "Healing Stream Totem", { baseTick = 9, mana = 70 }); -- Rank 4 (no coefficient in JSON)
S:Define(10463, T.SHAMAN, "Healing Stream Totem", { baseTick = 11, mana = 80 }); -- Rank 5 (no coefficient in JSON)
