#!/usr/bin/env python3
"""Generate Parsers/Talents_Generated.lua from the talentsforever.com JSON exports in .claude/docs.

Forever serves all three Classic talent trees of a class as one C_Traits tree whose nodes carry no
tree tag, and C_SpecializationInfo only knows a class-level "spec". The addon therefore needs its own
talent-name -> tab map to tell which tree the points went into (spec detection in Classes/Util.lua).

Usage:
    python tools/gen_talents.py          # (re)write Parsers/Talents_Generated.lua
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / ".claude" / "docs"
OUT = ROOT / "Parsers" / "Talents_Generated.lua"

# JSON file -> Lua class token (UnitClass second return).
CLASSES = {"druid": "DRUID", "paladin": "PALADIN", "priest": "PRIEST", "shaman": "SHAMAN"}


def collect():
    """{classToken: [(tabIndex, tabName, [talentName, ...]), ...]} in Classic tab order.
    Talents listed under a tree's `removed` key are not in Forever and are left out."""
    out = {}
    for cls, token in CLASSES.items():
        data = json.loads((DOCS / f"{cls}.json").read_text(encoding="utf-8"))
        out[token] = [(i + 1, tree["name"], [t["name"] for t in tree["talents"]])
                      for i, tree in enumerate(data["talents"]["trees"])]
    return out


HEADER = """-- GENERATED by tools/gen_talents.py from .claude/docs/{druid,paladin,priest,shaman}.json - do not edit by hand.
-- Talent name -> talent tab (1-3, Classic tree order) per class. Forever serves all three trees as one
-- C_Traits tree with no tree tag on the nodes, so tab membership has to come from here (Classes/Util.lua).
local name, addon = ...;

addon.TalentTab = {
"""


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(tabs):
    lines = [HEADER]
    for token in sorted(tabs):
        trees = tabs[token]
        lines.append(f"\t{token} = {{ -- " + ", ".join(f"{i} {n}" for i, n, _ in trees) + "\n")
        for i, _, names in trees:
            for n in names:
                lines.append(f"\t\t[{lua_str(n)}] = {i},\n")
        lines.append("\t},\n")
    lines.append("};\n")
    return "".join(lines)


def main(argv):
    tabs = collect()
    OUT.write_text(render(tabs), encoding="utf-8")
    count = sum(len(names) for trees in tabs.values() for _, _, names in trees)
    print(f"wrote {OUT.relative_to(ROOT)}: {count} talents")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
